import { t, getCurrentLang, hasTranslation } from './i18n.js';
import { CHECKED, COUNTRIES, US_STATES } from './region-data.js';
import { LOCALS_CHECKED, CURATED, KRAKEN, BINANCE, TRANSAK } from './region-curated.js';

// "Where you live changes the answer" (Guides › Marketplace › Funding and Cash out).
//
// One country picker, two answers. The member picks a country (and a state in the US),
// and each guide section rewrites its own block: which of the options above work there,
// over which bank rail, who locals use instead, and what to watch for. The two blocks
// share one pick, so choosing Brazil on the Cash out step already applies on Funding.
//
// Nothing here detects location. The site has no geo lookup and its CSP allows no
// third-party call that could do one; the pick is the member's own, stored in
// localStorage only (the copy says so). The one nudge is a browser-language hint, offered
// as a button, never applied on its own.
//
// Two data sources, kept apart on purpose:
//   js/region-data.js     GENERATED by scripts/build-region-data.mjs from MetaMask's and
//                         Transak's own coverage APIs. Never hand-edit; re-run the script.
//   js/region-curated.js  hand-checked, because these three publish no usable feed:
//                         Kraken's served list and payout currencies, Binance's entities,
//                         Coinbase per country, plus local venues and the country notes.
// A country in neither file still gets an honest answer. Every row has an "Unchecked"
// state that says we could not confirm it and points at the company's own signup screen,
// which is the one thing on this page that is always current.
//
// Every string is a t() key. Provider and venue names are brand names and stay as they
// are; country and currency names come from Intl.DisplayNames — see lang() vs uiLang()
// for which language each gets, and why they are not always the same one.

const KEY = 'hcc-region';

// The ten countries Highrise users come from most (owner's user-base numbers, September
// 2026), for the empty-state chips. Iran, Russia and Iraq stay on the list on purpose:
// "none of these serve you" is an answer worth one tap too.
const COMMON = ['US', 'IR', 'RU', 'TR', 'IQ', 'BR', 'CA', 'IN', 'EG', 'GB'];

const BRAND = {
  mm: { name: 'MetaMask Sell', logo: '/img/brands/metamask.svg' },
  cb: { name: 'Coinbase',      logo: '/img/brands/coinbase.svg' },
  kr: { name: 'Kraken',        logo: '/img/brands/kraken.svg' },
  bn: { name: 'Binance',       logo: '/img/brands/binance.svg', diamond: true },
};

// Domain pills print their own destination, registrable domain in bold: the same
// "read the address bar backwards" check the rules above the cards ask for.
const LINKS = {
  mm: { href: 'https://portfolio.metamask.io/sell', pre: 'portfolio.', dom: 'metamask.io', path: '/sell' },
  cb: { href: 'https://www.coinbase.com', pre: 'www.', dom: 'coinbase.com' },
  kr: { href: 'https://www.kraken.com',   pre: 'www.', dom: 'kraken.com' },
  tx: { href: '/trade/add-funds', pre: 'hcc.', dom: 'highrise.game', path: '/trade/add-funds', internal: true },
};

const CARD_SVG = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M3 7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/><path d="M3 10h18"/><path d="M6.5 14.8h3.6"/></svg>';
const BANK_SVG = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m3 9.5 9-5.5 9 5.5"/><path d="M5.5 10.5v8"/><path d="M10 10.5v8"/><path d="M14 10.5v8"/><path d="M18.5 10.5v8"/><path d="M2.8 20.8h18.4"/></svg>';

let pick = loadPick();      // { c: 'BR', s: null } — s is a US state code or null
let hintRegion = null;      // from the browser's language tags, offered, never applied
let roots = [];

// ---------- state ----------

function loadPick() {
  try {
    const p = JSON.parse(localStorage.getItem(KEY) || 'null');
    if (p && COUNTRIES[p.c]) return { c: p.c, s: p.c === 'US' && p.s && US_STATES[p.s] ? p.s : null };
  } catch {}
  return { c: null, s: null };
}
function savePick() {
  try { localStorage.setItem(KEY, JSON.stringify(pick)); } catch {}
}

// A region a member's browser already declares (pt-BR, tr-TR, es-MX). A lone en-US is
// the factory default on half the world's browsers, so it says nothing and is skipped.
function browserRegion() {
  const tags = (navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language]).filter(Boolean);
  if (tags.length === 1 && /^en-US$/i.test(tags[0])) return null;
  for (const tag of tags) {
    try {
      const r = new Intl.Locale(tag).region;
      if (r && COUNTRIES[r]) return r;
    } catch {}
  }
  return null;
}

// ---------- text helpers ----------

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
// Fill {token} placeholders. Values are escaped here, so the result is safe as HTML.
function fmt(key, vars = {}) {
  return String(t(key)).replace(/\{(\w+)\}/g, (m, k) => (k in vars ? esc(vars[k]) : m));
}
// The language to format country names, currencies, lists and dates in — which is the
// language this block's COPY resolved to, not the one the site is set to. The whole
// cash-out family is English-only and rides the fallback, so a Portuguese reader was
// getting English sentences with "Dólar americano" and "e" dropped into them. Ask i18n
// whether the active dictionary really has these strings; the day they're translated,
// this starts returning the reader's language on its own.
function lang() {
  return hasTranslation('gm.geo.country') ? uiLang() : 'en';
}
// The reader's actual language, for the two places where finding your own country beats
// matching the prose: the option labels and the order they're sorted in. A label is not a
// sentence, so nothing reads as half-translated there.
function uiLang() { return getCurrentLang() || 'en'; }
function displayNames(type, forLang) {
  try { return new Intl.DisplayNames([forLang || lang()], { type, fallback: 'code' }); } catch { return null; }
}
// English wants an article in front of some country names, and Intl doesn't supply one:
// "works in Philippines" and "pays out in United States" are the giveaway. The rule covers
// the plurals and the unions rather than listing 249 countries, with a short list for the
// ones no rule catches. Only for English prose — every other language handles this its own
// way, and a label in a dropdown never takes an article.
// The two Congos are deliberately absent: Intl's English names for them are
// "Congo - Kinshasa" and "Congo - Brazzaville", which take no article.
const THE_ALWAYS = new Set(['PH', 'NL', 'BS', 'MV', 'GM', 'KM', 'SC', 'IM', 'VA']);
function theName(name, c) {
  if (THE_ALWAYS.has(c) || /(Islands|Isles)$/.test(name) || /^United /.test(name) || / Republic$/.test(name)) return `the ${name}`;
  return name;
}
export function countryName(c, forLang) {
  const dn = displayNames('region', forLang);
  let n = null;
  try { n = dn && dn.of(c); } catch {}
  const name = n && n !== c ? n : (COUNTRIES[c]?.n || c);
  // The article belongs to prose, so only when this is the prose language and it's English.
  return !forLang && lang() === 'en' ? theName(name, c) : name;
}
function currencyName(code) {
  const dn = displayNames('currency');
  let n = null;
  try { n = dn && dn.of(code); } catch {}
  return n && n !== code ? n : code;
}
function joinList(items) {
  try { return new Intl.ListFormat(lang(), { type: 'conjunction' }).format(items); } catch { return items.join(', '); }
}
// Rail ids (pix, sepa, fps…) to words. An id with no key prints as itself rather than as
// a raw "gm.geo.rail.x", so a new rail in the data can never leak a key onto the page.
function railNames(ids) {
  return joinList((ids || []).map(id => { const k = `gm.geo.rail.${id}`; const s = t(k); return s === k ? id : s; }));
}
function fmtDate(iso) {
  try { return new Date(`${iso}T12:00:00Z`).toLocaleDateString(lang(), { day: 'numeric', month: 'long', year: 'numeric' }); } catch { return iso; }
}
function placeName(c, s) {
  return c === 'US' && s && US_STATES[s] ? US_STATES[s].n : countryName(c);
}

// ---------- the answer ----------

function pill(link, when) { return { ...link, when }; }
function global(id, rest) {
  return { id, kind: 'global', name: BRAND[id].name, logo: BRAND[id].logo, diamond: !!BRAND[id].diamond, open: id, ...rest };
}

// A row's name is a button that opens that option's dossier above it, so the two sections
// have to agree on which card that is. The cash-out section has one card per company; the
// funding section has two, "Card, on this site" and one "An exchange" card covering all
// three, so every exchange row there points at that one. Getting this wrong is a button
// that silently does nothing, which is why the mapping lives here and not in the markup.
const CARD_FOR = { funding: { tx: 'tx', cb: 'cex', kr: 'cex', bn: 'cex' } };
function cardFor(mode, id) {
  const map = CARD_FOR[mode];
  return map ? map[id] || null : id;
}
function binanceSite(c) {
  const site = BINANCE.sites[c] || BINANCE.sites.default;
  const when = site.whenKey ? t(site.whenKey) : undefined;
  return pill({ href: `https://${site.host}`, pre: site.host.slice(0, site.host.length - site.dom.length), dom: site.dom }, when);
}

// Binance answers half the question in public, and the page says which half.
//
// COUNTRIES[c].bn comes from Binance's own signup country list, where the United States and
// its territories, Cuba, Iran and North Korea are simply absent. But that list is evidence
// about a DROPDOWN, not about service: Canada and the Netherlands are still on it years
// after Binance announced it was leaving both. So a country on the list gets "Limited" and
// wording that claims no more than the list can carry, BINANCE.left overrides it with the
// announced exits, and the bank rail is never asserted at all — Binance publishes it
// nowhere, every fiat endpoint 404s, and the one fiat menu it serves mixes bank rails with
// person-to-person currencies. Curated `bn.st` wins wherever someone confirmed a real rail.
function binanceRow(c, s, mode, V) {
  const b = (CURATED[c] || {}).bn || {};
  const site = BINANCE.sites[c] || BINANCE.sites.default;
  const no = () => global('bn', { status: 'no', why: fmt('gm.geo.bn.no', V), links: [] });

  if (b.st === 'no') return no();
  // The United States is off binance.com entirely and served by a different company, so it
  // never falls through to the signup flag, which would only say "absent".
  if (c === 'US') {
    if (s && BINANCE.usNotServed.includes(s)) return no();
    if (s && BINANCE.usCryptoOnly.includes(s)) return global('bn', { status: 'ltd', why: fmt('gm.geo.bn.usCrypto', V), links: [binanceSite(c)] });
    return global('bn', { status: 'ltd', why: fmt('gm.geo.bn.us', V), links: [binanceSite(c)] });
  }
  if (BINANCE.restricted.includes(c) && !BINANCE.sites[c]) return no();
  // An announced exit beats the signup list, which still carries both of them.
  if (BINANCE.left[c]) return global('bn', { status: 'no', why: fmt('gm.geo.bn.left', { ...V, date: BINANCE.left[c] }), links: [] });
  // The MiCA suspension beats it too, and for the same reason: the signup list still
  // carries all thirty EEA countries months after Binance switched them off.
  if (BINANCE.mica.includes(c)) return global('bn', { status: 'no', why: fmt('gm.geo.bn.mica', { ...V, date: BINANCE.micaDate }), links: [] });
  if (BINANCE.blocked[c]) return global('bn', { status: 'no', why: fmt('gm.geo.bn.blocked', { ...V, date: BINANCE.blocked[c] }), links: [] });
  if (BINANCE.exiting[c]) return global('bn', { status: 'ltd', why: fmt('gm.geo.bn.exiting', { ...V, date: BINANCE.exiting[c], site: site.dom }), links: [binanceSite(c)] });
  if (BINANCE.frozen[c]) return global('bn', { status: 'ltd', why: fmt('gm.geo.bn.frozen', { ...V, date: BINANCE.frozen[c] }), links: [binanceSite(c)] });
  if (b.st === 'p2p') return global('bn', { status: 'ltd', why: fmt('gm.geo.bn.p2p', V), links: [binanceSite(c)] });
  if (b.st === 'ok') {
    const rails = b.rails && b.rails.length ? railNames(b.rails) : null;
    const key = mode === 'funding' ? (rails ? 'gm.geo.bn.buy' : 'gm.geo.bn.okNoRails') : (rails ? 'gm.geo.bn.ok' : 'gm.geo.bn.okNoRails');
    return global('bn', { status: 'ok', why: fmt(key, { ...V, site: site.dom, rails }), links: [binanceSite(c)] });
  }
  const signup = COUNTRIES[c].bn;
  if (signup === 0) return no();
  if (signup === 1) {
    const key = mode === 'funding' ? 'gm.geo.bn.acctBuy' : 'gm.geo.bn.acct';
    return global('bn', { status: 'ltd', why: fmt(key, { ...V, site: site.dom }), links: [binanceSite(c)] });
  }
  return global('bn', { status: 'unk', why: fmt('gm.geo.bn.unk', V), links: [binanceSite(c)] });
}

function krakenRow(c, s, mode, V) {
  const cu = (CURATED[c] || {}).kr || {};
  const served = cu.ok !== 0 && !KRAKEN.notServed.includes(c) && !(c === 'US' && s && KRAKEN.usNotServed.includes(s));
  const fiat = cu.fiat || (KRAKEN.fiat[V.cur] ? V.cur : null);
  const rails = cu.rails || (fiat && KRAKEN.fiat[fiat]) || [];
  if (!served) return global('kr', { status: 'no', why: fmt('gm.geo.kr.no', V), links: [] });
  if (!fiat) return global('kr', { status: 'ltd', why: fmt(mode === 'funding' ? 'gm.geo.kr.buyNoFiat' : 'gm.geo.kr.noFiat', V), links: [pill(LINKS.kr)] });
  const key = mode === 'funding' ? (rails.length ? 'gm.geo.cex.buy' : 'gm.geo.cex.buyNoRails') : (rails.length ? 'gm.geo.kr.ok' : 'gm.geo.cb.okNoRails');
  return global('kr', { status: 'ok', why: fmt(key, { ...V, rails: railNames(rails) }), links: [pill(LINKS.kr)] });
}

// Coinbase retired its public country feed, so there is no generated list to lean on and
// every state here comes from the curated file. Four answers, not two: it opens accounts
// in far more places than it pays a bank in, and the page must not blur the two.
function coinbaseRow(c, mode, V) {
  const cb = (CURATED[c] || {}).cb;
  if (!cb) return global('cb', { status: 'unk', why: fmt('gm.geo.cb.unk', V), links: [pill(LINKS.cb)] });
  if (cb.acct === 0) return global('cb', { status: 'no', why: fmt('gm.geo.cb.no', V), links: [] });
  const flag = mode === 'funding' ? (cb.buy ?? cb.cash) : cb.cash;
  const rails = cb.rails || [];
  if (flag === 1) {
    const key = mode === 'funding' ? (rails.length ? 'gm.geo.cex.buy' : 'gm.geo.cex.buyNoRails') : (rails.length ? 'gm.geo.cb.ok' : 'gm.geo.cb.okNoRails');
    return global('cb', { status: 'ok', why: fmt(key, { ...V, rails: railNames(rails) }), links: [pill(LINKS.cb)] });
  }
  if (flag === 0) return global('cb', { status: 'ltd', why: fmt('gm.geo.cb.convert', V), links: [pill(LINKS.cb)] });
  return global('cb', { status: 'ltd', why: fmt(mode === 'funding' ? 'gm.geo.cb.buyAcctOnly' : 'gm.geo.cb.acctOnly', V), links: [pill(LINKS.cb)] });
}

function metamaskRow(c, s, V) {
  const d = COUNTRIES[c];
  const st = c === 'US' && s ? US_STATES[s] : null;
  const mm = st ? st.mm : d.mm;   // [buy, sell]
  // A state answers for itself where MetaMask gives it its own list.
  const rails = (CURATED[c] || {}).mm?.rails || (st && st.mmRails) || d.mmRails || [];
  if (!mm[1]) return global('mm', { status: 'no', why: fmt(mm[0] ? 'gm.geo.mm.nosell' : 'gm.geo.mm.none', V), links: [] });
  const why = rails.length ? fmt('gm.geo.mm.ok', { ...V, rails: railNames(rails) }) : fmt('gm.geo.mm.okNoRails', V);
  return global('mm', { status: 'ok', why, links: [pill(LINKS.mm, t('gm.paid.go.mm.note'))] });
}

// Three states, because Transak's own feeds have three answers. A country its currency
// list covers is confirmed; one its document list blocks is a no; everything else is
// unconfirmed, and saying so beats telling someone in India the card doesn't work.
function transakRow(c, s, V) {
  const tx = COUNTRIES[c].tx;
  const blocked = c === 'US' && s && TRANSAK.usNotServed.includes(s);
  const row = { id: 'tx', kind: 'card', name: t('gm.get.card.name'), open: 'tx' };
  if (blocked || (tx && !tx.ok)) return { ...row, status: 'no', why: fmt('gm.geo.tx.no', V), links: [] };
  if (!tx) return { ...row, status: 'unk', why: fmt('gm.geo.tx.unk', V), links: [pill(LINKS.tx, t('gm.get.go.here'))] };
  const methods = tx.pay && tx.pay.length ? railNames(tx.pay) : null;
  return {
    ...row, status: 'ok',
    why: fmt(methods ? 'gm.geo.tx.ok' : 'gm.geo.tx.okNoMethods', { ...V, methods }),
    links: [pill(LINKS.tx, t('gm.get.go.here'))],
  };
}

function localRows(c, s, mode, V) {
  return ((CURATED[c] || {}).loc || []).flatMap(l => {
    if (mode === 'cashout' && l.sell === 0) return [];
    if (mode === 'funding' && l.buy === 0) return [];
    if (s && (l.notIn || []).includes(s)) return [];   // a venue its own state list rules out
    const link = pill({ href: `https://${l.d}`, pre: '', dom: l.d });
    const base = { id: `loc:${l.d}`, kind: 'local', name: l.n, reg: l.reg, links: [link] };
    if (mode === 'funding' && l.wd === 0) return [{ ...base, status: 'no', why: fmt('gm.geo.loc.noWd', V), links: [] }];
    const rails = l.rails && l.rails.length ? railNames(l.rails) : null;
    const key = mode === 'cashout' ? (rails ? 'gm.geo.loc.sell' : 'gm.geo.loc.sellNoRails') : (rails ? 'gm.geo.loc.buy' : 'gm.geo.loc.buyNoRails');
    return [{ ...base, status: 'ok', why: fmt(key, { ...V, rails }) }];
  });
}

// The cheapest route that actually pays (or takes) local money: published trading fees
// rank Binance under Kraken under Coinbase, and a vetted local venue closes the list.
function cheapest(rows) {
  for (const id of ['bn', 'kr', 'cb']) {
    const r = rows.find(x => x.id === id && x.status === 'ok');
    if (r) return r.name;
  }
  const loc = rows.find(x => x.kind === 'local' && x.status === 'ok');
  return loc ? loc.name : null;
}

function evaluate(mode, c, s) {
  const d = COUNTRIES[c];
  const V = { place: placeName(c, s), currency: currencyName(d.cur), cur: d.cur };
  const rows = [];
  const point = () => rows.forEach(r => { if (r.kind !== 'local') r.open = cardFor(mode, r.id); });
  // Under comprehensive sanctions the verdict is not "the cheapest of what's left", and
  // the fallback line about selling into dollars would be advice we can't stand behind.
  if ((CURATED[c] || {}).legal === 'sanctioned') {
    if (mode === 'cashout') rows.push(metamaskRow(c, s, V), coinbaseRow(c, 'cashout', V), krakenRow(c, s, 'cashout', V), binanceRow(c, s, 'cashout', V));
    else rows.push(transakRow(c, s, V), coinbaseRow(c, 'funding', V), krakenRow(c, s, 'funding', V), binanceRow(c, s, 'funding', V));
    point();
    return { rows, verdict: fmt('gm.geo.v.sanctioned', V) };
  }
  if (mode === 'cashout') {
    rows.push(metamaskRow(c, s, V), coinbaseRow(c, 'cashout', V), krakenRow(c, s, 'cashout', V), binanceRow(c, s, 'cashout', V), ...localRows(c, s, 'cashout', V));
    const first = rows[0].status === 'ok';
    const cheap = cheapest(rows);
    const key = first ? (cheap ? 'gm.geo.v.cash.mm' : 'gm.geo.v.cash.mmOnly') : (cheap ? 'gm.geo.v.cash.noMm' : 'gm.geo.v.cash.none');
    point();
    return { rows, verdict: fmt(key, { ...V, cheap }) };
  }
  rows.push(transakRow(c, s, V), coinbaseRow(c, 'funding', V), krakenRow(c, s, 'funding', V), binanceRow(c, s, 'funding', V), ...localRows(c, s, 'funding', V));
  const first = rows[0].status === 'ok';
  const cheap = cheapest(rows);
  const key = first ? (cheap ? 'gm.geo.v.fund.tx' : 'gm.geo.v.fund.txOnly') : (cheap ? 'gm.geo.v.fund.noTx' : 'gm.geo.v.fund.none');
  point();
  return { rows, verdict: fmt(key, { ...V, cheap }) };
}

// ---------- markup ----------

function pillHtml(l) {
  const ext = !l.internal;
  return `<a class="gm-go-link" href="${esc(l.href)}"${ext ? ' target="_blank" rel="noopener noreferrer"' : ''}>`
    + `<span class="gm-go-dom">${esc(l.pre || '')}<b>${esc(l.dom)}</b>${esc(l.path || '')}</span>`
    + (l.when ? ` <em class="gm-go-when">${esc(l.when)}</em>` : '')
    + ` <span class="gm-go-arrow" aria-hidden="true">${ext ? '↗' : '→'}</span></a>`;
}

function rowHtml(r, i) {
  let ico;
  if (r.kind === 'global') ico = `<span class="gm-geo-ico${r.diamond ? ' is-diamond' : ''}"><img src="${esc(r.logo)}" alt="" width="22" height="22"></span>`;
  else ico = `<span class="gm-geo-ico is-plain" aria-hidden="true">${r.kind === 'card' ? CARD_SVG : BANK_SVG}</span>`;
  const name = r.open
    ? `<button type="button" class="gm-geo-name" data-geo-open="${esc(r.open)}" title="${esc(t('gm.geo.open'))}">${esc(r.name)}</button>`
    : `<b class="gm-geo-name">${esc(r.name)}</b>`;
  const tag = r.kind === 'local' ? `<span class="gm-geo-tag">${esc(t('gm.geo.local'))}</span>` : '';
  const reg = r.reg ? `<span class="gm-geo-reg">${esc(r.reg)}</span>` : '';
  return `<li class="gm-geo-row is-${r.status}" style="--i:${i}">${ico}`
    + `<div class="gm-geo-main"><div class="gm-geo-hd">${name}<span class="gm-geo-st is-${r.status}">${esc(t(`gm.geo.st.${r.status}`))}</span>${tag}${reg}</div>`
    + `<p class="gm-geo-why">${r.why}</p></div>`
    + `<div class="gm-geo-links">${r.links.map(pillHtml).join('')}</div></li>`;
}

function emptyHtml(mode) {
  const chips = COMMON.filter(c => COUNTRIES[c])
    .map(c => `<button type="button" class="gm-geo-chip" data-geo-set="${c}">${esc(countryName(c, uiLang()))}</button>`).join('');
  return `<div class="gm-geo-empty"><p>${esc(t(`gm.geo.empty.${mode}`))}</p>`
    + (chips ? `<div class="gm-geo-common"><span class="gm-geo-common-l">${esc(t('gm.geo.common'))}</span>${chips}</div>` : '')
    + '</div>';
}

function resultHtml(mode, c, s) {
  const cu = CURATED[c] || {};
  const place = placeName(c, s);
  const ev = evaluate(mode, c, s);
  let alert = '';
  if (cu.legal === 'sanctioned') alert = `<p class="gm-geo-alert">${fmt('gm.geo.sanctioned', { place })}</p>`;
  else if (cu.legal === 'restricted' && cu.legalNote) alert = `<p class="gm-geo-alert is-soft">${esc(t(cu.legalNote))}</p>`;
  const noteKeys = [...(cu.notes || []), ...((mode === 'cashout' ? cu.notesCash : cu.notesFund) || [])];
  // The default note for a country nobody has written up. Two versions, because pointing a
  // reader at MetaMask's sell page is good advice only if MetaMask might sell there. When
  // MetaMask's own list says no AND MoonPay's independently agrees — MoonPay is one of the
  // companies behind that page, and its coverage is cross-checked at build time — sending
  // them off to confirm a refusal wastes their time.
  const d = COUNTRIES[c];
  const deadEnd = !d.mm[1] && d.mp && !d.mp[1];
  const notes = noteKeys.length
    ? `<ul>${noteKeys.map(k => `<li>${esc(t(`gm.geo.note.${k}`))}</li>`).join('')}</ul>`
    : `<p>${fmt(deadEnd ? 'gm.geo.notes.noneDead' : 'gm.geo.notes.none', { place })}</p>`;
  return `<div class="gm-geo-res">`
    + `<div class="gm-geo-verdict"><span class="gm-pick-tag">${fmt('gm.geo.in', { place })}</span><p>${ev.verdict}</p></div>`
    + alert
    + `<ul class="gm-geo-rows" role="list">${ev.rows.map(rowHtml).join('')}</ul>`
    + `<div class="gm-geo-notes"><b>${fmt('gm.geo.notes.h', { place })}</b>${notes}</div>`
    // One date when both halves were checked the same day, which is the usual case and
    // reads as a fact rather than as bookkeeping.
    + `<p class="gm-geo-fine">${CHECKED.date === LOCALS_CHECKED
        ? fmt('gm.geo.fine1', { date: fmtDate(CHECKED.date) })
        : fmt('gm.geo.fine', { date: fmtDate(CHECKED.date), date2: fmtDate(LOCALS_CHECKED) })}</p>`
    + '</div>';
}

// ---------- the selects ----------

function fillCountrySelect(sel) {
  const codes = Object.keys(COUNTRIES).map(c => [c, countryName(c, uiLang())]).sort((a, b) => a[1].localeCompare(b[1], uiLang()));
  sel.replaceChildren(
    new Option(t('gm.geo.pick'), '', true, !pick.c),
    ...codes.map(([c, n]) => new Option(n, c, false, c === pick.c)),
  );
  sel.value = pick.c || '';
}
function fillStateSelect(sel) {
  const states = Object.entries(US_STATES).sort((a, b) => a[1].n.localeCompare(b[1].n, 'en'));
  sel.replaceChildren(
    new Option(t('gm.geo.pickState'), '', true, !pick.s),
    ...states.map(([code, st]) => new Option(st.n, code, false, code === pick.s)),
  );
  sel.value = pick.s || '';
}

function renderRoot(root) {
  const mode = root.dataset.geo;
  const country = root.querySelector('[data-geo-country]');
  const state = root.querySelector('[data-geo-state]');
  const stateWrap = root.querySelector('[data-geo-statewrap]');
  const hint = root.querySelector('[data-geo-hint]');
  const out = root.querySelector('[data-geo-out]');
  if (country && country.value !== (pick.c || '')) country.value = pick.c || '';
  if (state && state.value !== (pick.s || '')) state.value = pick.s || '';
  if (stateWrap) stateWrap.hidden = pick.c !== 'US';
  if (hint) {
    const show = !!hintRegion && hintRegion !== pick.c && !pick.c;
    hint.hidden = !show;
    if (show) { hint.textContent = fmt('gm.geo.hint', { country: countryName(hintRegion) }); hint.dataset.geoSet = hintRegion; }
  }
  if (!out) return;
  if (!pick.c) { out.innerHTML = emptyHtml(mode); return; }
  if (pick.c === 'US' && !pick.s) { out.innerHTML = `<div class="gm-geo-empty"><p>${esc(t('gm.geo.needState'))}</p></div>`; return; }
  out.innerHTML = resultHtml(mode, pick.c, pick.s);
  // Glossary links for the prose we just wrote. Fetched, never imported: a decoration
  // must not be able to take the picker down with it.
  import('./glossary-link.js').then(m => m.linkGlossaryTerms(out)).catch(() => {});
}

function renderAll() { roots.forEach(renderRoot); }

function setCountry(c) {
  pick = COUNTRIES[c] ? { c, s: null } : { c: null, s: null };
  savePick();
  renderAll();
}
function setState(s) {
  pick.s = pick.c === 'US' && US_STATES[s] ? s : null;
  savePick();
  renderAll();
}

// Expand the matching option card above and bring it into view. Chromium ignores
// scroll-margin when a <details> is the scrollIntoView target, so the scroll is by hand.
function openCard(root, key) {
  const section = root.closest('.gm-paid');
  const card = section && section.querySelector(`.gm-opt[data-opt="${key}"]`);
  if (!card) return;
  card.open = true;
  const margin = parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--nav-clear')) || 80;
  const smooth = !matchMedia('(prefers-reduced-motion: reduce)').matches;
  window.scrollTo({ top: card.getBoundingClientRect().top + window.scrollY - margin - 8, behavior: smooth ? 'smooth' : 'instant' });
  card.querySelector('summary')?.focus({ preventScroll: true });
}

// ---------- public API ----------

export function initRegionPick() {
  roots = [...document.querySelectorAll('[data-geo]')];
  if (!roots.length) return;
  hintRegion = browserRegion();
  roots.forEach(root => {
    const country = root.querySelector('[data-geo-country]');
    const state = root.querySelector('[data-geo-state]');
    if (country) { fillCountrySelect(country); country.addEventListener('change', () => setCountry(country.value)); }
    if (state) { fillStateSelect(state); state.addEventListener('change', () => setState(state.value)); }
    // The controls ship hidden so a reader whose JS never arrives gets the static facts
    // instead of two empty dropdowns. They appear only once they can actually answer.
    const bar = root.querySelector('[data-geo-bar]');
    if (bar) bar.hidden = false;
    // Delegated: the chips, the hint and the card-openers are re-rendered on every change.
    root.addEventListener('click', e => {
      const set = e.target.closest?.('[data-geo-set]');
      if (set && root.contains(set)) { setCountry(set.dataset.geoSet); root.querySelector('[data-geo-country]')?.focus(); return; }
      const open = e.target.closest?.('[data-geo-open]');
      if (open && root.contains(open)) openCard(root, open.dataset.geoOpen);
    });
  });
  renderAll();
}

// After translations load and on every language switch: country names, labels and the
// answer all change language, and the selects have to be rebuilt to re-sort.
export function rerenderRegionPick() {
  roots.forEach(root => {
    const country = root.querySelector('[data-geo-country]');
    const state = root.querySelector('[data-geo-state]');
    if (country) fillCountrySelect(country);
    if (state) fillStateSelect(state);
  });
  renderAll();
}
